export const getPasteles = () => {
    return new Promise(resolve => {
        resolve({
            tortasFrias: {
                menu: '/tortas-frias/menu',
                cover: '/tortas-frias/portada',
                tortas: [
                    {
                        id: 1,
                        name: 'Torta Fría de Maracuyá Entera',
                        description: 'Deliciosa torta fría de Maracuyá entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'maracuya-entera'
                    },
                    {
                        id: 2,
                        name: 'Torta Fría de Maracuyá por Porción',
                        description: 'Deliciosa torta fría de Maracuyá por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'maracuya-tajada',
                    },
                    {
                        id: 3,
                        name: 'Torta Fría de Melocotón Entera',
                        description: 'Deliciosa torta fría de Melocoton entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'melocoton-entera',
                    },
                    {
                        id: 4,
                        name: 'Torta Fría de Melocotón por Porción',
                        description: 'Deliciosa torta fría de Melocotón por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'melocoton-tajada',
                    },
                    {
                        id: 5,
                        name: 'Torta Fría de Piña Colada Entera',
                        description: 'Deliciosa torta fría de Piña Colada entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'pinacolada-entera',
                    },
                    {
                        id: 6,
                        name: 'Torta Fría de Piña Colada por Porción',
                        description: 'Deliciosa torta fría de Piña Colada por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'pinacolada-tajada',
                    },
                    {
                        id: 7,
                        name: 'Torta Fría de Tiramizú Entera',
                        description: 'Deliciosa torta fría de Tiramizú entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'tiramizu-entera',
                    },
                    {
                        id: 8,
                        name: 'Torta Fría de Tiramizú por Porción',
                        description: 'Deliciosa torta fría de Tiramizú por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'tiramizu-tajada',
                    },
                    {
                        id: 9,
                        name: 'Torta Fría de Snicker Entera',
                        description: 'Deliciosa torta fría de Snicker entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'snicker-entera',
                    },
                    {
                        id: 10,
                        name: 'Torta Fría de Snicker por Porción',
                        description: 'Deliciosa torta fría de Snicker por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'snicker-tajada',
                    },
                    {
                        id: 11,
                        name: 'Torta Fría de Rompope y Frutas Entera',
                        description: 'Deliciosa torta fría de Rompope y Frutas entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'rompopefrutas-entera',
                    },
                    {
                        id: 12,
                        name: 'Torta Fría de Rompope y Frutas por Porción',
                        description: 'Deliciosa torta fría de Rompope y Frutas por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'rompopefrutas-tajada',
                    },
                    {
                        id: 13,
                        name: 'Torta Fría de Pie de Limón Entera',
                        description: 'Deliciosa torta fría de Pie de Limón entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'pielimon-entera',
                    },
                    {
                        id: 14,
                        name: 'Torta Fría de Pie de Limón por Porción',
                        description: 'Deliciosa torta fría de Pie de Limón por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'pielimon-tajada',
                    },
                    {
                        id: 15,
                        name: 'Torta Fría de Pasión de Caramelo Entera',
                        description: 'Deliciosa torta fría de Pasión de Caramelo entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'pasioncaramelo-entera',
                    },
                    {
                        id: 16,
                        name: 'Torta Fría de Pasión de Caramelo por Porción',
                        description: 'Deliciosa torta fría de Pasión de Caramelo por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'pasioncaramelo-tajada',
                    },
                    {
                        id: 17,
                        name: 'Torta Fría Navideña Entera',
                        description: 'Deliciosa torta fría Navideña entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'navidena-entera',
                    },
                    {
                        id: 18,
                        name: 'Torta Fría Navideña por Porción',
                        description: 'Deliciosa torta fría Navideña por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'navidena-tajada',
                    },
                    {
                        id: 19,
                        name: 'Torta Fría de Naranja Holandesa Entera',
                        description: 'Deliciosa torta fría de Naranja Holandesa entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'naranjaholandesa-entera',
                    },
                    {
                        id: 20,
                        name: 'Torta Fría de Naranja Holandesa por Porción',
                        description: 'Deliciosa torta fría de Naranja Holandesa por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'naranjaholandesa-tajada',
                    },
                    {
                        id: 21,
                        name: 'Torta Fría de Mora y Fresas Entera',
                        description: 'Deliciosa torta fría de Mora y Fresas entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'morafresa-entera',
                    },
                    {
                        id: 22,
                        name: 'Torta Fría de Mora y Fresas por Porción',
                        description: 'Deliciosa torta fría de Mora y Fresas por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'morafresa-tajada',
                    },
                    {
                        id: 23,
                        name: 'Torta Fría de Higos y Ron Entera',
                        description: 'Deliciosa torta fría de Higos y Ron entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'higosron-entera',
                    },
                    {
                        id: 24,
                        name: 'Torta Fría de Higos y Ron por Porción',
                        description: 'Deliciosa torta fría de Higos y Ron por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'higosron-tajada',
                    },
                    {
                        id: 25,
                        name: 'Torta Fría de Galleta Oreo Entera',
                        description: 'Deliciosa torta fría de Galleta Oreo entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'galletaoreo-entera',
                    },
                    {
                        id: 26,
                        name: 'Torta Fría de Galleta Oreo por Porción',
                        description: 'Deliciosa torta fría de Galleta Oreo por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'galletaoreo-tajada',
                    },
                    {
                        id: 27,
                        name: 'Torta Fría de Churchill Entera',
                        description: 'Deliciosa torta fría de Churchill entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'churchill-entera',
                    },
                    {
                        id: 28,
                        name: 'Torta Fría de Churchill por Porción',
                        description: 'Deliciosa torta fría de Churchill por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'churchill-tajada',
                    },
                    {
                        id: 29,
                        name: 'Torta Fría de Choco Menta Entera',
                        description: 'Deliciosa torta fría de Choco Menta entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'chocomenta-entera',
                    },
                    {
                        id: 30,
                        name: 'Torta Fría de Choco Menta por Porción',
                        description: 'Deliciosa torta fría de Choco Menta por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'chocomenta-tajada',
                    },
                    {
                        id: 31,
                        name: 'Torta Fría de Chocofresa Entera',
                        description: 'Deliciosa torta fría de Chocofresa entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'chocofresa-entera',
                    },
                    {
                        id: 32,
                        name: 'Torta Fría de Chocofresa por Porción',
                        description: 'Deliciosa torta fría de Chocofresa por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'chocofresa-tajada',
                    },
                    {
                        id: 33,
                        name: 'Torta Fría de Choco Coco Entera',
                        description: 'Deliciosa torta fría de Choco Coco entera',
                        path: '/tortas-frias/tortas/',
                        filename: 'chocococo-entera',
                    },
                    {
                        id: 34,
                        name: 'Torta Fría de Choco Coco por Porción',
                        description: 'Deliciosa torta fría de Choco Coco por porción',
                        path: '/tortas-frias/tortas/',
                        filename: 'chocococo-tajada',
                    },
                ]
            }
        })
    })
}